# Generated by Django 5.2.15 on 2026-06-27 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('transfer', 'Transfer'), ('loan_payment', 'Loan Payment'), ('interest', 'Interest'), ('fee', 'Fee'), ('food', 'Food & Dining'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20)),
                ('recipient_account', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
